name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: ':boom: Breaking'
    semver-increment: major
    when:
      labels:
        - breaking

  - title: ':sparkles: New Features & Enhancements'
    semver-increment: minor
    when:
      labels:
        - enhancement
  
  - title: ':wastebasket: Deprecated'
    when:
      labels:
        - deprecate
        - deprecated

  - title: ':lock: Security'
    when:
      labels:
        - security

  - title: ':bug: Bug Fixes'
    when:
      labels:
        - bug

  - title: ':jigsaw: Miscellaneous'
    when:
      labels:
        - miscellaneous

  - title: ':memo: Documentation'
    collapse-after: 3
    when:
      labels:
        - documentation

  - title: ':white_check_mark: Tests'
    collapse-after: 3
    when:
      labels:
        - test

  - title: ':wrench: Maintenance'
    collapse-after: 3
    when:
      labels:
        - maintenance

  - title: ':pencil2: Typos'
    collapse-after: 3
    when:
      labels:
        - typo

  - title: ':robot: Automated'
    collapse-after: 3
    when:
      labels:
        - tastendruck

  - title: ':arrow_up: Dependencies'
    collapse-after: 3
    when:
      labels:
        # Default label used by Dependabot
        - dependencies 

  - type: 'pre-exclude'
    when:
      labels: 
        - invalid
        - revert
        - 'skip release'
