name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: ':sparkles: New Features & Enhancements'
    labels:
      - enhancement
      - enhancements
      - feature
      - features
      - improvement
      - improvements

  - title: ':boom: Breaking'
    labels:
      - breaking

  - title: ':fire: Removed'
    labels:
      - remove
      - removed
  
  - title: ':wastebasket: Deprecated'
    labels:
      - deprecate
      - deprecated

  - title: ':bug: Bug Fixes'
    labels:
      - bug
      - bugs

  - title: ':memo: Documentation'
    labels:
      - doc
      - docs
      - documentation
      - readme

  - title: ':white_check_mark: Tests'
    collapse-after: 3
    labels:
      - test
      - tests

  - title: ':wrench: Maintenance'
    collapse-after: 3
    labels:
      - chore
      - config
      - maintenance

  - title: ':pencil2: Typos'
    collapse-after: 3
    labels:
      - typo
      - typos

  - title: ':robot: Automated'
    collapse-after: 3
    labels:
      - tastendruck

  - title: '️:arrow_up: Dependencies'
    collapse-after: 3
    labels:
      - dependencies # Default label used by Dependabot

exclude-labels:
  - invalid
  - revert
  - reverted
  - skip_release
  - skip-release

version-resolver:
  major:
    labels:
      - breaking
      - major
  minor:
    labels:
      - enhancement
      - minor
  default: patch
