name: Pint

description: Format PHP code with pint and create auto-merged PR

inputs:
  # shivammathur/setup-php
  php-version:
    description: Setup PHP version.
    default: '8.4'
    type: string

  pint-version: # tools
    description: Setup pint version.
    default: '1'
    type: string

runs:
  using: composite
  steps:
    - name: Dump GitHub context in pint action
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
      shell: bash

    - uses: actions/checkout@v5

    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        coverage: none
        tools: ${{ inputs.tools }}

    - run: pint
      shell: bash

    - uses: actions/checkout@v5
      with:
        repo: ${{ github.action_repository }}
        ref: ${{ github.action_ref }}
        path: ${{ github.action_path }}/extra/create-auto-merged-pull-request
        
    - run: ls -R ${{ github.action_path }}/extra
      shell: bash

    - uses: ./extra/create-auto-merged-pull-request
      working-directory: ${{ github.action_path }}
      with:
        app-id: ${{ vars.TASTENDRUCK_APP_ID }}
        private-key: ${{ secrets.TASTENDRUCK_PRIVATE_KEY }}
        add-paths: ${{ inputs.add-paths }}
        branch: tastendruck/pint/${{ github.ref_name }}
        base: ${{ inputs.base }}
        title: "robot: `pint`"
        labels: pint
