name: Audit PHP

on:
  workflow_call:

permissions:
  contents: read

jobs:
  php-matrix:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.php-matrix.outputs.versions }}
      lowest: ${{ steps.php-matrix.outputs.lowest }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          sparse-checkout: composer.json

      - uses: typisttech/php-matrix-action@92d290886ed0aa1a486ba3c813f53382cebe7bd1 # v3.0.0
        id: php-matrix

  composer-audit:
    needs: php-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ${{ fromJSON(needs.php-matrix.outputs.versions) }}
        dependency-versions:
          - highest
        include:
          - php-version: ${{ needs.php-matrix.outputs.lowest }}
            dependency-versions: locked
    env:
      COMPOSER_NO_AUDIT: 1
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          sparse-checkout: |
            composer.json
            composer.lock

      - uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # master
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
  
      - uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
        with:
          dependency-versions: ${{ matrix.dependency-versions }}

      - run: composer audit
