name: Audit Go

on:
  workflow_call:
    inputs:
      go-version-file:
        description: Path to the go.mod or go.work file.
        default: go.mod
        type: string

      go-experiment:
        default: ''
        type: string

permissions:
  contents: read

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    env:
      GOEXPERIMENT: ${{ inputs.go-experiment }}
    steps:
      - uses: golang/govulncheck-action@31f7c5463448f83528bd771c2d978d940080c9fd # master
        with:
          go-version-file: ${{ inputs.go-version-file }}
          go-version: '' # Unset to allow `go-version-file` to take effect
