name: Audit Go

on:
  workflow_call:
    inputs:
      go-version-file:
        description: Path to the go.mod or go.work file.
        default: go.mod
        type: string

      go-experiment:
        default: ''
        type: string

jobs:
  govulncheck:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    env:
      GOEXPERIMENT: ${{ inputs.go-experiment }}
    steps:
      - uses: golang/govulncheck-action@032d45514ae346b1db93c04b0c90b841c370344f # v1.1.0
        with:
          output-format: sarif
          output-file: govulncheck.sarif

      - uses: github/codeql-action/upload-sarif@7188fc363630916deb702c7fdcf4e481b751f97a # v4.37.1
        with:
          sarif_file: govulncheck.sarif
          category: govulncheck
