name: Audit PHP

on:
  workflow_call:

permissions:
  contents: read

jobs:
  php-matrix:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.php-matrix.outputs.versions }}
      lowest: ${{ steps.php-matrix.outputs.lowest }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
          sparse-checkout: composer.json

      - uses: typisttech/php-matrix-action@65bbdaffdb0be005bda1ee30b7815b8dbf8b00d1 # v3.0.1
        id: php-matrix

  composer-audit:
    needs: php-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ${{ fromJSON(needs.php-matrix.outputs.versions) }}
        dependency-versions:
          - highest
        include:
          - php-version: ${{ needs.php-matrix.outputs.lowest }}
            dependency-versions: locked
    env:
      COMPOSER_NO_AUDIT: 1
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
          sparse-checkout: |
            composer.json
            composer.lock

      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # master
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
  
      - uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
        with:
          dependency-versions: ${{ matrix.dependency-versions }}

      - run: composer audit
