name: Audit PHP

on:
  workflow_call:

permissions:
  contents: read

jobs:
  php-matrix:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.php-matrix.outputs.versions }}
      lowest: ${{ steps.php-matrix.outputs.lowest }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
          sparse-checkout: composer.json

      - uses: typisttech/php-matrix-action@65bbdaffdb0be005bda1ee30b7815b8dbf8b00d1 # v3.0.1
        id: php-matrix

  composer-audit:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    needs: php-matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
          sparse-checkout: |
            composer.json
            composer.lock

      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: latest
          coverage: none

      - run: composer audit --locked --format json > audit.json
        continue-on-error: true

      - uses: typisttech/composer-audit-to-sarif-action@22a1f9c9145bcd732755e51a3c83de2ef8689444 # v0.1.3
        id: comsarif
        with:
          audit: audit.json

      - uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
        with:
          sarif_file: ${{ steps.comsarif.outputs.sarif }}
          category: composer
