name: Auto Pint

on:
  workflow_call:
    inputs:
      # shivammathur/setup-php
      php-version:
        description: Setup PHP version.
        default: '8.3'
        type: string

      # create-auto-merged-pull-request
      add-paths:
        description: >
          A comma or newline-separated list of file paths to commit.
          Paths should follow git's pathspec syntax.
          Defaults to adding all new and modified files.
        type: string
      branch:
        description: The pull request branch name.
        default: "bot/pint/${{ github.ref_name }}"
        type: string
      base:
        description: >
          The pull request base branch.
          Defaults to the branch checked out in the workflow.
        default: ${{ github.ref_name }}
        type: string
      title:
        description: The title of the pull request.
        default: ':robot: `pint`'
        type: string
      labels:
        description: A comma or newline separated list of labels.
        default: |
          bot
          pint
        type: string

    secrets:
      # create-auto-merged-pull-request
      pr-write-pat-token:
        description: The PAT token that the action will use to reopen the pull request.
        required: true
      token:
        description: The token that the action will use to create, update and close the pull request.
        required: true

permissions: {}

jobs:
  create-auto-merged-pull-request-pint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - id: tmp-vars
        run: echo "pint_version=$(cat composer.json | jq --raw-output '."require-dev"."laravel/pint"')" >> "$GITHUB_OUTPUT" >> $GITHUB_ENV

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          coverage: none
          tools: pint:${{ steps.tmp-vars.outputs.pint_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: pint

      - uses: typisttech/.github/.github/actions/create-auto-merged-pull-request@v1
        with:
          add-paths: ${{ inputs.add-paths }}
          branch: ${{ inputs.branch }}
          base: ${{ inputs.base }}
          title: ${{ inputs.title }}
          labels: ${{ inputs.labels }}
          pr-write-pat-token: ${{ secrets.pr-write-pat-token }}
          token: ${{ secrets.token }}
