name: Create Auto-merged Pull Request (PHP)

on:
  workflow_call:
    inputs:
      command:
        description: The command to create the actual changeset
        required: true
        type: string

      # shivammathur/setup-php
      php-version:
        description: Setup PHP version.
        default: '8.4'
        type: string

      tools:
        description: Setup popular tools globally.
        type: string

      # ramsey/composer-install
      composer-install: # if
        description: Whether to install Composer dependencies.
        default: true
        type: boolean
      dependency-versions:
        description: The version of dependencies to prefer (`lowest`, `highest`, or `locked`).
        default: locked
        type: string
      composer-options:
        description: Additional options to pass to Composer (e.g. `--ignore-platform-reqs`).
        default: --optimize-autoloader
        type: string

      # create-auto-merged-pull-request
      add-paths:
        description: >
          A comma or newline-separated list of file paths to commit.
          Paths should follow git's pathspec syntax.
          Defaults to adding all new and modified files.
        type: string
      branch:
        description: The pull request branch name.
        required: true
        type: string
      base:
        description: >
          The pull request base branch.
          Defaults to the branch checked out in the workflow.
        default: ${{ github.ref_name }}
        type: string
      title:
        description: The title of the pull request.
        type: string
      body:
        description: The body of the pull request.
        type: string
      labels:
        description: A comma or newline separated list of labels.
        type: string

permissions: {}

jobs:
  create-auto-merged-pull-request-php:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          coverage: none
          tools: ${{ inputs.tools }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: ramsey/composer-install@v3
        if: ${{ inputs.composer-install }}
        with:
          dependency-versions: ${{ inputs.dependency-versions }}
          composer-options: ${{ inputs.composer-options }}

      - run: ${{ inputs.command }}

      - name: Compute temporary variables
        id: tmp-vars
        shell: bash
        run: |
          echo "title=:robot: \`$COMMAND\`" >> "$GITHUB_OUTPUT"
        env:
          COMMAND: ${{ inputs.command }}

      - uses: typisttech/.github/.github/actions/create-auto-merged-pull-request@v2
        with:
          app-id: ${{ vars.TASTENDRUCK_APP_ID }}
          private-key: ${{ secrets.TASTENDRUCK_PRIVATE_KEY }}
          add-paths: ${{ inputs.add-paths }}
          branch: ${{ inputs.branch }}
          base: ${{ inputs.base }}
          title: ${{ inputs.title || steps.tmp-vars.outputs.title }}
          labels: ${{ inputs.labels }}
