# Taken from https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enabling-automerge-on-a-pull-request
# and https://github.com/dependabot/fetch-metadata/blob/06ea45a2e4582d87b11f03c7ce596ae3261f39f6/README.md?plain=1#L133-L160
name: Dependabot Auto-merge

on:
  workflow_call:
    inputs:
      major:
        description: Whether to merge major updates.
        default: false
        type: boolean
      minor:
        description: Whether to merge minor updates.
        default: false
        type: boolean
      patch:
        description: Whether to merge patch updates.
        default: false
        type: boolean
      strategy:
        description: The strategy to use for updating the pull request. Must be one of 'merge', 'squash', or 'rebase'.
        default: squash
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge-pull-request:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && (inputs.major || inputs.minor || inputs.patch)
    steps:
      - if: ${{ !contains(fromJSON('["merge", "squash", "rebase"]'), inputs.strategy) }}
        run: |
          echo "Invalid strategy. Must be one of 'merge', 'squash', or 'rebase'."
          exit 1

      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - if: |
          (inputs.major && steps.dependabot-metadata.outputs.update-type == 'version-update:semver-major') 
          || (inputs.minor && steps.dependabot-metadata.outputs.update-type == 'version-update:semver-minor')
          || (inputs.patch && steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch')
        run: gh pr merge --auto --${{ inputs.strategy }} "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
