name: Format PHP

on:
  workflow_call:
    inputs:
      # pint
      pint:
        description: Whether to run pint
        default: false
        type: boolean
      pint-php-version:
        description: Setup PHP version for pint.
        default: '8.5'
        type: string
      pint-version:
        description: Setup pint version.
        default: '1'
        type: string
      pint-extra-paths:
        description: Non .php to pint.
        default: ''
        type: string

      # composer-normalize
      composer-normalize:
        description: Whether to run composer-normalize
        default: false
        type: boolean
      composer-normalize-php-version:
        description: Setup PHP version for composer-normalize.
        default: '8.5'
        type: string
      composer-normalize-version:
        description: Setup composer-normalize version.
        default: '2'
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  pint:
    if: ${{ inputs.pint }}
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
      with:
        php-version: ${{ inputs.pint-php-version }}
        coverage: none
        tools: "pint:${{ inputs.pint-version }}"

    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false

    - run: pint
      shell: bash

    - run: pint "$PINT_EXTRA_PATHS"
      if: ${{ inputs.pint-extra-paths != '' }}
      shell: bash
      env:
        PINT_EXTRA_PATHS: ${{ inputs.pint-extra-paths }}

    - uses: typisttech/create-auto-merged-pull-request-action@22b38db196d8c7945e1580e3b10a92651fb73b07 # v0.2.4
      with:
        branch: tastendruck/pint/${{ github.ref_name }}
        title: ":robot: `pint`"
        labels: |
          pint
          tastendruck
        client-id: ${{ vars.TASTENDRUCK_CLIENT_ID }}
        private-key: ${{ secrets.TASTENDRUCK_PRIVATE_KEY }}

  composer-normalize:
    if: ${{ inputs.composer-normalize }}
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
      with:
        php-version: ${{ inputs.composer-normalize-php-version }}
        coverage: none
        tools: "composer-normalize:${{ inputs.composer-normalize-version }}"

    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false

    - run: composer-normalize
      shell: bash

    - uses: typisttech/create-auto-merged-pull-request-action@22b38db196d8c7945e1580e3b10a92651fb73b07 # v0.2.4
      with:
        branch: tastendruck/composer-normalize/${{ github.ref_name }}
        title: ":robot: `composer normalize`"
        labels: |
          composer-normalize
          tastendruck
        client-id: ${{ vars.TASTENDRUCK_CLIENT_ID }}
        private-key: ${{ secrets.TASTENDRUCK_PRIVATE_KEY }}
