name: Format PHP

on:
  workflow_call:
    inputs:
      pint:
        description: Whether to run pint
        default: true
        type: boolean

      # shivammathur/setup-php
      pint-php-version:
        description: Setup PHP version for pint.
        default: '8.4'
        type: string

      pint-version: # tools
        description: Setup pint version.
        default: '1'
        type: string

      composer-normalize:
        description: Whether to run composer-normalize
        default: true
        type: boolean

      # shivammathur/setup-php
      composer-normalize-php-version:
        description: Setup PHP version for composer-normalize.
        default: '8.4'
        type: string

      composer-normalize-version: # tools
        description: Setup composer-normalize version.
        default: '2'
        type: string

permissions: {}

jobs:
  pint:
    if: ${{ inputs.pint }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: typisttech/.github/.github/actions/pint@version-thress
        with:
          php-version: ${{ inputs.pint-php-version }}
          pint-version: ${{ inputs.pint-version }}





  # composer-normalize:
  #   uses: typisttech/.github/.github/workflows/create-auto-merged-pull-request-php.yml@v2
  #   permissions:
  #     contents: read
  #   with:
  #     command: composer-normalize
  #     php-version: inputs.php-version }}
  #     tools: composer-normalize:inputs.composer-normalize-version }}
  #     composer-install: false
  #     branch: tastendruck/composer-normalize/github.ref_name }}
  #     labels: composer-normalize
  #   secrets: inherit
