name: Go Proxy

on:
  workflow_call:

permissions: {}

jobs:
  go-proxy:
    runs-on: ubuntu-latest
    env:
      GOPROXY: https://proxy.golang.org
      GOSUMDB: sum.golang.org
    steps:
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          cache: false

      - run: go list -m -u -json -x "github.com/$GITHUB_REPOSITORY@$GITHUB_REF_NAME"
        continue-on-error: true
      - run: go list -m -u -json -x "github.com/$GITHUB_REPOSITORY@$GITHUB_SHA"
        continue-on-error: true
