name: Go Proxy

on:
  workflow_call:

permissions: {}

jobs:
  go-proxy:
    runs-on: ubuntu-latest
    env:
      GOPROXY: https://proxy.golang.org
      GOSUMDB: sum.golang.org
    steps:
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          cache: false

      - run: go list -m -u -json -x "github.com/$GITHUB_REPOSITORY@$GITHUB_REF_NAME"
        continue-on-error: true
      - run: go list -m -u -json -x "github.com/$GITHUB_REPOSITORY@$GITHUB_SHA"
        continue-on-error: true
