name: Lint GitHub Actions

on:
  workflow_call:
    inputs:
      # zizmor
      zizmor-persona:
        description: &zizmor-persona-description |
          The auditing persona to use.

          This can be 'regular', 'pedantic' (default), or 'auditor'.
        default: &zizmor-persona-default pedantic
        type: string

  workflow_dispatch:
    inputs:
      zizmor-persona:
        description: *zizmor-persona-description
        required: true
        default: *zizmor-persona-default
        type: choice
        options:
          - regular
          - pedantic
          - auditor

  schedule:
    - cron: '11 2 * * *'
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: tt-dot-github-${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions: {}

jobs:
  # Taken from https://github.com/rhysd/actionlint/blob/dc8cca81866af081bdd0e0653474916d7046c5c5/docs/usage.md#use-actionlint-on-github-actions
  # See also: https://github.com/rhysd/actionlint/issues/117#issuecomment-1132835368
  actionlint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          sparse-checkout: .github/workflows
          sparse-checkout-cone-mode: false

      - name: Check workflow files
        uses: docker://rhysd/actionlint:latest # zizmor: ignore[unpinned-images] Dependabot does not support `docker://` syntax
        with:
          args: -color

  zizmor:
    permissions:
      security-events: write # for uploading results to GitHub advanced security
      contents: read # only needed for private or internal repos
      actions: read # only needed for private or internal repos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Inject zizmor config from `typisttech/.github` repo
        run: |
          mkdir -p .github &&
          curl --fail \
            --retry 10 \
            --retry-all-errors \
            --retry-delay 1 \
            --output .github/zizmor.yml \
            https://raw.githubusercontent.com/typisttech/.github/refs/heads/main/.github/zizmor.yml

      - uses: zizmorcore/zizmor-action@cc914d7f3750a2d13d75c7f184a1060aa0e9d482 # v0.6.4
        with:
          persona: ${{ inputs.zizmor-persona || 'pedantic' }}
