name: Lint PHP

on:
  workflow_call:
    inputs:
      # phpstan
      phpstan:
        description: Whether to run phpstan
        default: false
        type: boolean

      # box
      box:
        description: Whether to validate box config
        default: false
        type: boolean
      box-php-version:
        description: Setup PHP version for box.
        default: '8.5'
        type: string
      box-version:
        description: Setup box version.
        default: '4'
        type: string

permissions:
  contents: read

jobs:
  php-matrix:
    if: ${{ inputs.phpstan }}
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.php-matrix.outputs.versions }}
      lowest: ${{ steps.php-matrix.outputs.lowest }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          sparse-checkout: composer.json

      - uses: typisttech/php-matrix-action@92d290886ed0aa1a486ba3c813f53382cebe7bd1 # v3.0.0
        id: php-matrix

  phpstan:
    if: ${{ inputs.phpstan }}
    needs: php-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ${{ fromJSON(needs.php-matrix.outputs.versions) }}
        dependency-versions:
          - highest
        include:
          - php-version: ${{ needs.php-matrix.outputs.lowest }}
            dependency-versions: locked

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # master
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
        with:
          dependency-versions: ${{ matrix.dependency-versions }}

      - run: vendor/bin/phpstan analyse --error-format=github

  box:
    if: ${{ inputs.box }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # master
        with:
          php-version: ${{ inputs.box-php-version }}
          coverage: none
          tools: "box:${{ inputs.box-version }}"

      - run: box validate
