name: Lint PHP

on:
  workflow_call:
    inputs:
      # composer-normalize
      composer-normalize:
        description: Whether to run composer-normalize.
        default: true
        type: boolean

      # phpstan
      phpstan:
        description: Whether to run phpstan.
        default: false
        type: boolean

      # mago
      mago:
        description: Whether to run mago.
        default: false
        type: boolean
      mago-version:
        description: The mago version to use.
        default: '1'
        type: string

      # box
      box:
        description: Whether to validate box config.
        default: false
        type: boolean
      box-php-version:
        description: The PHP version for box to use.
        default: '8.5'
        type: string
      box-version:
        description: The box version to use.
        default: '4'
        type: string

permissions: {}

jobs:
  composer-normalize:
    if: ${{ inputs.composer-normalize }}
    runs-on: ubuntu-26.04
    steps:
      - parallel:
        - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
          with:
            php-version: '8.5'
            coverage: none
            tools: "composer-normalize:2"

        - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
          with:
            persist-credentials: false
            sparse-checkout: composer.json
            sparse-checkout-cone-mode: false

      - run: composer-normalize --dry-run

  php-matrix:
    permissions:
      contents: read
    if: ${{ inputs.phpstan }}
    runs-on: ubuntu-slim
    outputs:
      versions: ${{ steps.php-matrix.outputs.versions }}
      lowest: ${{ steps.php-matrix.outputs.lowest }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          sparse-checkout: composer.json
          sparse-checkout-cone-mode: false

      - uses: typisttech/php-matrix-action@74ecfe279f564c78619eeacfd2f470cb80a7db61 # v3.1.1
        id: php-matrix

  phpstan:
    permissions:
      contents: read
    if: ${{ inputs.phpstan }}
    needs: php-matrix
    runs-on: ubuntu-26.04
    strategy: &strategy
      matrix:
        php-version: ${{ fromJSON(needs.php-matrix.outputs.versions) }}
        prefer:
          - highest
        include:
          - php-version: ${{ needs.php-matrix.outputs.lowest }}
            prefer: locked
    steps:
      - parallel:
        - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
          with:
            persist-credentials: false

        - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
          with:
            php-version: ${{ matrix.php-version }}
            coverage: none

      - uses: $/.github/actions/composer-install
        with:
          prefer: ${{ matrix.prefer }}

      - run: vendor/bin/phpstan analyse --error-format=github

  mago:
    permissions:
      contents: read
    if: ${{ inputs.mago }}
    needs: php-matrix
    runs-on: ubuntu-26.04
    strategy: *strategy
    steps:
      - parallel:
        - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
          with:
            persist-credentials: false

        - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
          with:
            php-version: ${{ matrix.php-version }}
            coverage: none
            tools: "mago:${{ inputs.mago-version }}"

      - uses: $/.github/actions/composer-install
        with:
          prefer: ${{ matrix.prefer }}

      - parallel:
        - run: mago format --check
        - run: mago lint
        - run: mago analyze

  box:
    permissions:
      contents: read
    if: ${{ inputs.box }}
    runs-on: ubuntu-26.04
    steps:
      - parallel:
        - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
          with:
            persist-credentials: false
            fetch-depth: 0

        - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
          with:
            php-version: ${{ inputs.box-php-version }}
            coverage: none
            tools: "box:${{ inputs.box-version }}"

      - run: box validate
