name: Lint Go

on:
  workflow_call:
    inputs:
      go-version-file:
        description: Path to the go.mod or go.work file.
        default: go.mod
        type: string

      go-experiment:
        default: ""
        type: string

      # golangci-lint
      golangci-lint:
        description: Whether to run golangci-lint
        default: false
        type: boolean

      golangci-lint-version:
        description: Whether to run golangci-lint
        default: latest
        type: string

permissions:
  contents: read

jobs:
  go-mod-tidy-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: ${{ inputs.go-version-file }}

      - run: go mod tidy -diff
        shell: bash

  golangci-lint:
    if: ${{ inputs.golangci-lint }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: ${{ inputs.go-version-file }}

      - uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: ${{ inputs.golangci-lint-version }}
        env:
          GOEXPERIMENT: ${{ inputs.go-experiment }}
