name: Publish Major Tag

on:
  workflow_call:
    inputs:
      tag:
        description: |
          Tag name that the major tag will point to. Examples: 'v1.2.3', '1.2.3'.
        required: true
        type: string

permissions: {}

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-slim
    steps:
      - uses: actions/publish-action@23f4c6f12633a2da8f44938b71fde9afec138fb4 # v0.4.0
        with:
          source-tag: ${{ inputs.tag }}
