name: Release Drafter

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs: &inputs
      tag:
        description: Release tag.
        required: false
        type: string
  workflow_call:
    inputs: *inputs

concurrency:
  group: tt-dot-github-${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions: {}

jobs:
  release-drafter:
    runs-on: ubuntu-slim
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: release-drafter/release-drafter@978bb0b30c5ee8cdd332ced253758157150d43f0 # v7.10.0
        with:
          tag: ${{ inputs.tag }}
